modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory (36 is current forge version)
issueTrackerURL="https://github.com/MinecraftModDevelopmentMods/OreSpawn/issues/" #optional
# GNU LGPLv2.1 
license="GNU LGPLv2.1"
[[mods]] #mandatory
modId="orespawn" #mandatory
version="${file.jarVersion}" #mandatory
displayName="MMD OreSpawn" #mandatory
updateJSONURL="" # blank for now!
displayURL="https://github.com/MinecraftModDevelopmentMods/OreSpawn/"
logoFile="orespawn.png" #optional
authors="Dr. Plantabyte (aka: Cyanobacterium, Dr. Cyano), Jriwanek, DShadowWolf, others" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
A Mod for generating ore deposits in the world. Does not contain dragon girlfriends, mobs or anything like that
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.orespawn]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
    
[[dependencies.orespawn]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,)"
    ordering="NONE"
    side="BOTH"